
ENV = "Pendulum-v0"

DISPLAY = True
LOAD = False


FRAME_SKIP = 0

THREADS = 8
LIMIT_RUN_TIME = 360

EPSILON_START = 0.7
EPSILON_STOP = 0.05
EPSILON_STEPS = THREADS*2000
EPSILON_DECAY = (EPSILON_START - EPSILON_STOP) / EPSILON_STEPS

MAX_GRADIENT_NORM = 40

CRITIC_LEARNING_RATE = 1e-3
ACTOR_LEARNING_RATE = 1e-3
CRITIC_REG = 0.01

MAX_LEN_BUFFER = 128
MAX_EPISODE_STEP = 200

DISCOUNT = 0.99

# Display Frequencies
DISP_EP_REWARD_FREQ = 250
PLOT_FREQ = 1000

SAVE_FREQ = 5000
EP_ELONGATION = 500