
ENV = "CartPole-v0"

LOAD = False
DISPLAY = True

CONV = False

DISCOUNT = 0.99
NB_ATOMS = 51
MIN_VALUE = 0
MAX_VALUE = 8

LEARNING_RATE = 7.5e-4


FRAME_SKIP = 0
BUFFER_SIZE = 100000
BATCH_SIZE = 64

# Number of episodes of game environment to train with
TRAINING_STEPS = 100000
PRE_TRAIN_STEPS = 10000

# Maximal number of steps during one episode
MAX_EPISODE_STEPS = 200
TRAINING_FREQ = 10

# Rate to update target network toward primary network
UPDATE_TARGET_RATE = 0.05


EPSILON_START = 0.8
EPSILON_STOP = 0.01
EPSILON_STEPS = 10000
EPSILON_DECAY = (EPSILON_START - EPSILON_STOP) / EPSILON_STEPS

# Display Frequencies
DISP_EP_REWARD_FREQ = 250
PLOT_FREQ = 500
RENDER_FREQ = 2500

SAVE_FREQ = 20000
GIF_FREQ = 10000
MAX_NB_GIF = 5
EP_ELONGATION = 50
